spring:
  application:
    name: StudentMicro
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/microservice
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 8081
